import Head from "next/head";
import Image from "next/image";

import About from "../components/About";
import Contact from "../components/Contact";
import Hero from "../components/Hero";
import Skill from "../components/Skill";
import Project from "../components/Project";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Navbar />
      <Head>
        <title>Portfolio | Theeranai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-t.ico" />
      </Head>
      <Hero />
      <About />
      <Skill />
      <Project />
      {/* <Contact /> */}
    </div>
  );
}
